version: '2'
services:
  server:
    image: "j-bro/revenue-recognition"
    ports:
      - '8080:8080'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb
  mariadb:
    image: 'j-bro/revenue-recognition-sql'
    ports:
          - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
